FROM nvidia/cuda:12.6.0-cudnn-devel-ubuntu22.04
RUN apt-get update
RUN apt-get install vim git wget -y
WORKDIR /home/pyscf/
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    bzip2 \
    ca-certificates \
    libglib2.0-0 \
    libxext6 \
    libsm6 \
    libxrender1 \
    git \
    && rm -rf /var/lib/apt/lists/*
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    chmod +x /tmp/miniconda.sh && \
    /tmp/miniconda.sh -b -p /opt/conda && \
    rm /tmp/miniconda.sh
RUN conda update -n base -c defaults conda -y && \
    conda clean -afy
SHELL ["/bin/bash","-c"]
RUN conda init bash
RUN git clone https://github.com/pyscf/gpu4pyscf.git
RUN cd gpu4pyscf && pip install -e .
RUN pip install jupyter notebook
ENTRYPOINT []
#ENTRYPOINT ["jupyter" "lab"]
CMD ["jupyter" "lab" "--ip=0.0.0.0" "--no-browser" "--port=8888" "--NotebookApp.token=''" "--NotebookApp.password=''" "--allow-root" "--ContentsManager.allow_hidden=True"]
